"""AWS WAF (Web Application Firewall) Integration
Automatically pushes malicious IPs to AWS WAF IP Sets to block cloud-based attacks.
"""

import logging
from typing import List
from ..config import settings
import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)

class AWSWafClient:
    def __init__(self):
        # Requires boto3 to be installed and AWS credentials configured in environment
        self.enabled = getattr(settings, "AWS_WAF_ENABLED", False)
        self.ipset_id = getattr(settings, "AWS_WAF_IPSET_ID", None)
        self.ipset_name = getattr(settings, "AWS_WAF_IPSET_NAME", "NeevTIPBlocklist")
        self.region = getattr(settings, "AWS_REGION", "us-east-1")
        self.scope = getattr(settings, "AWS_WAF_SCOPE", "CLOUDFRONT") # or REGIONAL
        
        if self.enabled:
            # Note: in real production, credentials would load via IAM roles or env vars natively by boto3
            self.client = boto3.client('wafv2', region_name=self.region)

    def export_to_waf(self, ipv4_list: List[str]) -> bool:
        """Pushes a list of IPv4 addresses directly to the mapped AWS WAF IPSet."""
        if not self.enabled or not self.client or not self.ipset_id:
            logger.debug("AWS WAF integration not fully configured or disabled.")
            return False

        try:
            # 1. Fetch the current LockToken (WAFv2 requires lock tokens for state changes)
            response = self.client.get_ip_set(
                Name=self.ipset_name,
                Scope=self.scope,
                Id=self.ipset_id
            )
            lock_token = response['LockToken']

            # 2. Format IPs (AWS WAF requires CIDR notation for all IPs, e.g., /32)
            cidr_formatted_ips = []
            for ip in ipv4_list:
                if "/" not in ip:
                    cidr_formatted_ips.append(f"{ip}/32")
                else:
                    cidr_formatted_ips.append(ip)

            # 3. Update the IPSet
            self.client.update_ip_set(
                Name=self.ipset_name,
                Scope=self.scope,
                Id=self.ipset_id,
                Addresses=cidr_formatted_ips,
                LockToken=lock_token,
                Description="Automated blocklist generated by Neev TIP"
            )
            
            logger.info(f"Successfully pushed {len(ipv4_list)} IPs to AWS WAF IPSet {self.ipset_name}.")
            return True

        except ClientError as e:
            logger.error(f"AWS WAF API Error: {e}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error pushing to AWS WAF: {e}")
            return False

aws_waf_sync = AWSWafClient()
